// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOZNIMU84mnmD9ROuUJdcObovjuYagiQ0',
    appId: '1:138963872599:web:a170fccdcae61206846c12',
    messagingSenderId: '138963872599',
    projectId: 'flutter-test-709ee',
    authDomain: 'flutter-test-709ee.firebaseapp.com',
    storageBucket: 'flutter-test-709ee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYP_LX6xrZIBVbh7mOcajnuzKN7nh9sIk',
    appId: '1:138963872599:android:72c7284d8722e4c2846c12',
    messagingSenderId: '138963872599',
    projectId: 'flutter-test-709ee',
    storageBucket: 'flutter-test-709ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX7kvmX8lYvQOsY0DskfdN8hWAQWMWbUk',
    appId: '1:138963872599:ios:ddec5fdd578fe6d9846c12',
    messagingSenderId: '138963872599',
    projectId: 'flutter-test-709ee',
    storageBucket: 'flutter-test-709ee.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX7kvmX8lYvQOsY0DskfdN8hWAQWMWbUk',
    appId: '1:138963872599:ios:ddec5fdd578fe6d9846c12',
    messagingSenderId: '138963872599',
    projectId: 'flutter-test-709ee',
    storageBucket: 'flutter-test-709ee.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
